### ISSUE TITLE
Logging in using super-admin=1 doesn't work

### ISSUE THREAD

**Issue by gfarrell** [gfarrell/WPRavenAuth#36]
Gets this error:

    <b>Fatal error</b>:  Uncaught exception 'WPRavenAuth\AuthException' with message 'Raven Authentication not completed.' in /societies/kcsu/public_html/kcsu/wp-content/plugins/WPRavenAuth/app/core/raven.php:91
    Stack trace:
    #0 /societies/kcsu/public_html/kcsu/wp-content/plugins/WPRavenAuth/WPRavenAuth.php(108): WPRavenAuth\Raven-&gt;login()
    #1 [internal function]: WPRavenAuth\login_init('')
    #2 /societies/kcsu/public_html/kcsu/wp-includes/plugin.php(496): call_user_func_array('WPRavenAuth\log...', Array)
    #3 /societies/kcsu/public_html/kcsu/wp-login.php(446): do_action('login_init')
    #4 {main}
      thrown in <b>/societies/kcsu/public_html/kcsu/wp-content/plugins/WPRavenAuth/app/core/raven.php</b> on line <b>91</b><br />

**Comment by Burgch** [comment]
I can log in using super-admin=1, to the webmaster account. That looks a lot like the error you'd get if you had clicked cancel on the Raven login, easiest way to check would be to try again in a private browsing session.

**Comment by gfarrell** [comment]
Oh well, there goes my attempt to circumvent Raven login. Doesn't work without a Raven account.

**Comment by Burgch** [comment]
Sure it does; I'll send you the webmaster login details; you should be able to login without a raven account.

**Comment by gfarrell** [comment]
Oh. Every time I try it redirects me to Raven...


On 30 March 2015 at 18:10:11, Conor Burgess (notifications@github.com) wrote:

Sure it does; I'll send you the webmaster login details; you should be able to login without a raven account.

**Comment by Burgch** [comment]
Try using the webmaster account; it redirects you if you get the password wrong, which I should be able to fix.

**Comment by gfarrell** [comment]
Tried it, still redirects me to Raven.

**Comment by Burgch** [comment]
That's very strange, in a private browsing window I can login with the webmaster account using ?super-admin=1

Conor

**Comment by Burgch** [comment]
It now says the password is incorrect... :/
