### ISSUE TITLE
super-admin issue

### ISSUE THREAD

**Issue by RGunning** [gfarrell/WPRavenAuth#37]
I'm hitting an issue whilst trying to login with ?super-admin=1
I'm being taken to the correct login screen, however, after entering the username and password I'm being directed to raven login which overrides the login details

Any thoughts?

**Comment by gfarrell** [comment]
Similar to the issue I was having in #36, @Burgch. Root problem is, I think, that the cantab lookup service is used to get user details, which requires crsid? It's been a while since I looked at the codebase though so could be completely wrong.

**Comment by Burgch** [comment]
I'll take a look tomorrow. Should be fixable. I'm pretty sure I've worked out how to fix.

Conor

**Comment by RGunning** [comment]
Turns out it does work and I was just entering the wrong username.

Using the wrong username takes you to the raven screen

**Comment by Burgch** [comment]
Yup, I've found similar results; correct username and password works fine, anything else has an undefined outcome...

**Comment by Burgch** [comment]
Ok, should now work with incorrect usernames and all.
