### ISSUE TITLE
Defining own Lookup Groups for custom visibility

### ISSUE THREAD

**Issue by mhhadfield** [gfarrell/WPRavenAuth#38]
Hi Guys, 
First of all this is a beautiful plugin and you are all champions :)

Is it possible to add new Lookup Groups to the custom visibility options on this module along with the Colleges?
Thanks,
Meredith

**Comment by Burgch** [comment]
What were you thinking of Meredith? I may be able to suggest the code to add for other groups, but I wasn't planning to add more options to the plugin.

**Comment by mhhadfield** [comment]
Thanks for such a quick reply -
I was thinking of adding in each of our PHD and MPhil Students for
Criminology - Working on getting a CMS which can hold raven protected pages
& Documents.... these will probably need appending each year so it's not
the end of the workd if it's custom code our end.
At present we have no CMS on crim.cam.ac.uk and was hoping to get our
course administrators able to upload timetables etc themselves with more
granular permissions (ambitious! :D )
Thanks ,
Meredith

**Comment by Burgch** [comment]
Are all of the people defined by some lookup group? One of the institutions under http://www.lookup.cam.ac.uk/inst/CRIM <http://www.lookup.cam.ac.uk/inst/CRIM> for example?

Conor

**Comment by mhhadfield** [comment]
Yeah, they get put in as children institutions :)
Meredith

**Comment by Burgch** [comment]
So as I see it, you have two options, in both cases you'll need to modify the options available in `app/core/custom_fields.php`, by modifying `getVisibilityOptions` to something like:
```php
function getVisibilityOptions()
{
    global $available_colleges;
    $colleges = Config::get('colleges'); 
    $output = array(
                     'public' => 'Public',
                     'raven'  => 'Require Raven',
                    );
    if (is_array($colleges))
    {
        foreach ($colleges as $college)
        {
            $output = array_merge($output, $available_colleges[$college]);
        }
    }
    $output = array_merge($output, array('INST-CRIM' => 'All Criminology Members'));
    return $output;
}
```
Your options are then whether you want to just manually add all of the possible children institutions as visibility options in their own right (which you'd do by including them as extra entries in the array above), or if you just want to accept anyone who is a member of one of the child insts of the CRIM inst. The latter would require a few additions to `app/core/ibis.php`. You'll need to modify `getPerson` : 
```php
    public static function getPerson($crsid)
    {
        $pm = Ibis::ibisPM();
        return $pm->getPerson("crsid", $crsid, "jdCollege,all_insts.parent_insts");
    }
``` 
(note the addition of `parent_insts`), then maybe add an `isMemberOfInstOrChildInst` method:
```php
public static function isMemberOfInstOrChildInst($person, $instID)
    {
        $result = false;
        foreach ($person->institutions as $inst)
        {
            if (strcmp($inst->instid, $instID) == 0) || ((count($inst->parentInsts) > 0) && (strcmp($inst->parentInsts[0]->instid, $instID) == 0))
            {
                $result = true;
                break;
            }
        }
        return $result;
    }
```
This should allow you to check if a member is in the CRIM inst or a child inst of the CRIM inst, and you could then call this method from `WPRavenAuth` in the `userCanAccessPost` method, replacing the call to `isMemberOfInstOrChildInst`. Using this method, you could just add the CRIM inst to the options, and then anyone who is a member of that or a child of that would get access.

**Comment by mhhadfield** [comment]
Thanks for this I will give it a spin now!
Meredith

**Comment by mhhadfield** [comment]
Thanks so much! This works beautifully! I used the first method and it's
happy as anything :)

**Comment by Burgch** [comment]
No problem :)
