### ISSUE TITLE
Lookup 'friendly' names instead of crsid for username

### ISSUE THREAD

**Issue by GiantKiwi** [gfarrell/WPRavenAuth#41]
Was wondering how to extend this plugin so that when a user logs in, it makes their username their Firstname/Lastname instead of CRSid. I've seen that an older plugin (by Daniel Hill) on the Raven Wiki does what I need, would it be possible to adapt the functions in that relating to lookup to work with this?

Thanks,

Iain van Gardingen
Web Developer, Girton College (iv255)

**Comment by Burgch** [comment]
Yes, it would, but the name you get from the API depends on the user's privacy settings. If they were to change their settings, you'd get a different username, and then it would fail to recognise that they already had an account and create a new user. Furthermore, there's no guarantee that any two usernames would be unique, which is exactly the purpose of a CRSid. 

For these reasons, this plugin was designed to only use CRSid as username. That being said, there's no reason it couldn't attempt to populate the Wordpress User's name fields with the information from Lookup (Ibis).

**Comment by GiantKiwi** [comment]
I was meaning more along the lines of their display name not being their crsid, sorry if that led to confusion. So the system would still reference their username as the crsid, but their display name would be what is their default name that other users would see. Currently got system in place for arranging swimming buddies for the girton pool, but unless each user is diligent and edits their own profile to change their name, there are just reams of seemingly anonymous crsid's which it would appear is turning away the users who requested the system be implemented.

**Comment by Burgch** [comment]
Yeah, should be a straightforward fix for new users. May take a little more thinking about for existing users.

Conor

**Comment by Burgch** [comment]
I've just added something for new users, but as I no longer have a valid (current) Raven login, would you be able to test it?

**Comment by GiantKiwi** [comment]
I'll get on that as soon as i'm in the office.
