### ISSUE TITLE
Backing-out of Raven re-auth breaks wp-login

### ISSUE THREAD

**Issue by caiw** [gfarrell/WPRavenAuth#42]
Steps to reproduce:

1. Try to access wp-login page. Get redirected to Raven auth page.
1. Log in to Raven. Get redirected to WP site.
1. Log out of WP site.
1. Go to wp-login page. Get redirected to Raven auth page which notices you're still identified to Raven and offers option to re-autherise the WP site. ![re-identify](https://cloud.githubusercontent.com/assets/5602172/10666713/44eb408c-78cb-11e5-9985-7e5d1c2977ea.jpg)
1. Click cancel.
1. Fatal error on WP site (uncaught exception "Raven Authentication not completed."). ![exception](https://cloud.githubusercontent.com/assets/5602172/10666712/44d19e70-78cb-11e5-8f48-ef4d1fb51497.jpg)
1. Accessing wp-login now always produces error page.

To fix:

1. Clear cookies.

Found using:

1. Firefox 41.0.1.

**Comment by Burgch** [comment]
I'll take a look. Out of interest, what happens if you just cancel the first time you get to the raven login page? 

Conor

**Comment by caiw** [comment]
Don't know why I didn't check this before.  The same uncaught exception trace gets shown.

**Comment by Burgch** [comment]
I've just pushed a change to fix this; it'll now catch the error and display it nicely in the wordpress login page, along with a link to try again. I've tested it a bit, but without a current Raven login, it's a bit tricky. Could you test please and then I'll mark this closed?

**Comment by caiw** [comment]
Yep, works great now. Thank you!

**Comment by Burgch** [comment]
This wasn't actually a correct fix; it overhandled exceptions, and could result in valid users being logged out mid-way through authentication. I've fixed it properly in e94e21b
