### ISSUE TITLE
WP Debugging errors

### ISSUE THREAD

**Issue by mhhadfield** [gfarrell/WPRavenAuth#46]
Hi Guys,
I'm getting the following issues on 4.9.8 :  

Deprecated: Non-static method WPRavenAuth\Config::get() should not be called statically in /replicated/www/default/docroot/wp-content/plugins/WPRavenAuth/app/core/custom_fields.php on line 254

Deprecated: Non-static method WPRavenAuth\Raven::getInstance() should not be called statically in /replicated/www/default/docroot/wp-content/plugins/WPRavenAuth/WPRavenAuth.php on line 68

Deprecated: Non-static method WPRavenAuth\Config::get() should not be called statically in /replicated/www/default/docroot/wp-content/plugins/WPRavenAuth/WPRavenAuth.php on line 75

Is this a 'my site' issue or something which can be ignored?
Thanks,
Meredith

**Comment by Burgch** [comment]
Hopefully fixed by 04a3076089ad450a2a5754e28f0aa0e33b22bd29 - could you let me know if you're still seeing any errors?

**Comment by mhhadfield** [comment]
It's using the new MWS machine on Debian 9 which I think is using stretch(?)It's now only giving this one error:

Notice: Only variables should be passed by reference in /replicated/www/default/docroot/wp-content/plugins/WPRavenAuth/WPRavenAuth.php on line 24
