### ISSUE TITLE
Lookup Certificate

### ISSUE THREAD

**Issue by mhhadfield** [gfarrell/WPRavenAuth#47]
Here is the error we get:

<b>Warning</b>:  fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in <b>C:\www\trin.cam.ac.uk\wp-content\plugins\WPRavenAuth-master\app\lib\ibis-client\ibisclient\client\IbisClientConnection.php</b> on line <b>333</b><br />
<br />
<b>Warning</b>:  fopen(): Failed to enable crypto in <b>C:\www\trin.cam.ac.uk\wp-content\plugins\WPRavenAuth-master\app\lib\ibis-client\ibisclient\client\IbisClientConnection.php</b> on line <b>333</b><br />
<br />
<b>Warning</b>:  fopen(https://www.lookup.cam.ac.uk/api/v1/person/crsid/ap896?fetch=jdCollege%2Call_insts&amp;flatten=true): failed to open stream: operation failed in <b>C:\www\trin.cam.ac.uk\wp-content\plugins\WPRavenAuth-master\app\lib\ibis-client\ibisclient\client\IbisClientConnection.php</b> on line <b>333</b><br />
<br />

I've emailed the UIS who confirmed that this isn't a raven error but to do with the LDAP changes made recently. I've forwarded the error on to the Lookup UIS team. 
Meredith

**Comment by Burgch** [comment]
Thanks Meredith!

**Comment by mhhadfield** [comment]
Edited above

**Comment by mhhadfield** [comment]
Reply from AIS TLDR: 

To fix the problem, you will need to update WPRavenAuth to use the latest copy of the Ibis client library from here http://dev.csi.cam.ac.uk/trac/lookup/browser/trunk/downloads/php

**Comment by mhhadfield** [comment]
@Burgch  is it possible to edit the lookup link in the plugin to the new location?
thanks,
Meredith

**Comment by Burgch** [comment]
I’m not able to access the updated Ibis client as I’m not a current student. If you’re feeling generous, you could download it and submit a pull request!

**Comment by mhhadfield** [comment]
I will attempt the thing!
Meredith

**Comment by mhhadfield** [comment]
The site tells me I am not authorised to make a pull or to make a fork, but please find a zip with the lib/ibis-client folder replaced with the new one:
[WPRaven.zip](https://github.com/gfarrell/WPRavenAuth/files/2832160/WPRaven.zip)

**Comment by gfarrell** [comment]
@mhhadfield you should be able to fork the repo as it is a public repo, you won't be able to commit directly to this repo without being made a collaborator, but if you make a fork and open a PR then @Burgch should be able to review and merge.
