### ISSUE TITLE
Redirect loses PHP arguments

### ISSUE THREAD

**Issue by mleming** [gfarrell/WPRavenAuth#49]
I have a page on my website that requires a PHP argument to work, but when a user clicks on it and they need to log in to the website, it's stripped off upon the redirect. So right now the page is public (and I'd like it to be private). Is there any way to fix this?

**Comment by Burgch** [comment]
Can you clarify what you mean by PHP arguments? Do you mean $_GET or $_POST variables, or something else?

Conor

**Comment by mleming** [comment]
Sorry -- like, if the user clicks on the link mywordpresswebsite.com/?myvar=1, but that page is Raven-protected, then they sign in to Raven and it redirects to mywordpresswebsite.com/ and leaves myvar blank.

**Comment by Burgch** [comment]
You can work around this by preserving myvar in the session, and then retrieving it when you get redirected back to your page.

**Comment by mleming** [comment]
Could I accomplish that by editing the PHP code input on a page (seems doubtful), or would it require making my own custom updates to WPRavenAuth?

**Comment by Burgch** [comment]
I'm a bit confused - how are you forcing the user to login? WPRavenAuth
doesn't redirect to Raven unless the user visits the login page. If the
user tries to view a post that they don't have visibility rights for,
there's an option to try logging in - is that where you're experiencing
the problem?

**Comment by mleming** [comment]
Never mind, I'm an idiot. Fixed it using session_start() magic.
