### ISSUE TITLE
Plugin failing to load

### ISSUE THREAD

**Issue by bilal-chughtai** [gfarrell/WPRavenAuth#51]
Hi,

I recently updated our JCR website to wordpress 5.2.2 after not having updated it in probably a year, and WPRavenAuth seems to have broken. Here's the error I'm hitting:

```
An error of type E_ERROR was caused in line 88 of the file /public/societies/thjcr/public_html/wp-content/plugins/WPRavenAuth-master/app/core/raven.php. Error message: Uncaught WPRavenAuth\AuthException: in /public/societies/thjcr/public_html/wp-content/plugins/WPRavenAuth-master/app/core/raven.php:88

Stack trace:
#0 /public/societies/thjcr/public_html/wp-content/plugins/WPRavenAuth-master/WPRavenAuth.php(89): WPRavenAuth\Raven->login  
#1 /public/societies/thjcr/public_html/wp-includes/class-wp-hook.php(286): WPRavenAuth\login_init('')
#2 /public/societies/thjcr/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /public/societies/thjcr/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /public/societies/thjcr/public_html/wp-login.php(478): do_action('login_init')
#5 {main} 
thrown


```

**Comment by Burgch** [comment]
It looks like you don't have the latest version of the plugin - could you try downloading it from Github or updating your git clone to the latest code?

**Comment by bilal-chughtai** [comment]
This has fixed it! Both versions of the plugin are showing up at v1.0.0 in the WP UI. May be worth updating that?

**Comment by Burgch** [comment]
Fair point - we probably should have bumped the patch version. As the plugin isn’t distributed through the normal means it wouldn’t be updated by Wordpress itself anyway, so we’ve never really bothered with it. Anyway, glad you’re back up and running!
