### ISSUE TITLE
Only first INST matched

### ISSUE THREAD

**Issue by ehk20** [gfarrell/WPRavenAuth#52]
After some testing it seems to me that the check against Institution only passes if the matches the first result from lookup? Is this correct? ie. I can only control access to content if (in my case) I enable Darwin College (which is the first result) but not on St Edmund's College (which is the 2nd as per my lookup entry: https://www.lookup.cam.ac.uk/person/crsid/ehk20).

**Comment by Burgch** [comment]
I'll try to find some time to look into this over Christmas/New Year.

**Comment by Burgch** [comment]
I had a quick look and it looks like the University are using some new institutions to manage multiple college affiliations. I've updated the Custom Fields to support this - could you try updating that file, and see if the new "Institution Members" options fix your problem?

**Comment by ehk20** [comment]
> On 17 Dec 2019, at 14:24, Conor Burgess <notifications@github.com> wrote:
> 
> I had a quick look and it looks like the University are using some new institutions to manage multiple college affiliations. I've updated the Custom Fields to support this - could you try updating that file, and see if the new "Institution Members" options fix your problem?
> 
Yes. That seems to work (as originally intended?). I hadn’t noticed there was a COLL-* and guess it might be hold-over from Jackdaw’s ‘Affiliation/Residence/College’ structure since “College” in my case is Darwin in Jackdaw with no other values. I also note that in web look College points to https://www.lookup.cam.ac.uk/inst/DARWIN suggesting INST is indeed intended to replace COLL. Swapping to INST- seems to solve the problem as it will pick up multiple values available for INST. I’ve copied in lookup-admin in case someone there can see a reason for COLL- we’ve missed.

Espen

**Comment by Burgch** [comment]
Yeah, originally this plugin relied solely on the `jdCollege` attribute (short for Jackdaw College I believe?), but as you correctly surmise that can only be populated with a single `COLL` entry, which tends to be the first college you affiliate to. We therefore added support for the `INST` entries, which we request with `all_insts` when looking up a person. Previously students would only be a member of the e.g. `KINGSUG` or `KINGSPG` institution, as well as having the `jdCollege` attribute, but it looks like everyone now has an affiliation with one of the "main" e.g. `KINGS` institutions, so hopefully that will work going forwards.

**Comment by ehk20** [comment]
Yes. There is now two concepts which may come in to play: Child Institutions (as listed on https://www.lookup.cam.ac.uk/inst/EDMUND ) but also "Members groups” where a group can be created with a setting to indicate that it’s members are members of an institution. For example: https://www.lookup.cam.ac.uk/group/edmund-bye-fellows has this set to EDMUND as per the instruction that: "If this group represents the members of an institution, enter the ID of the institution here.”  Members of this and similar group get reported for the INST/EDMUND without having to be explicitly added to this top level INST and thus for practical purposes the solution you have suggested should capture that without further work.

Thanks!

Espen
