### ISSUE TITLE
Ibis Client update

### ISSUE THREAD

**Issue by mo-g** [gfarrell/WPRavenAuth#53]
UIS has updated the ibis client to reflect a cert change on Lookup. The new client now uses system cert stores. Worth updating the embedded copy here? :)

Source for new library: https://gitlab.developers.cam.ac.uk/uis/devops/iam/ibis/ibis-client/-/blob/master/downloads/php/ibis-php-client-api-1.3.0-src.tar.bz2

**Comment by Burgch** [comment]
Thanks for pointing this out - any chance you'd be able to give it a go and report back / create a pull request? I don't currently have time to support this I'm afraid.

**Comment by danielchriscarter** [comment]
I'm not the original creator of this issue, but I've just created a pull request which hopefully incorporates this update.

Thanks for your work on this project!

**Comment by mo-g** [comment]
Whoops! Thanks Daniel - I completely forgot about this!
