### ISSUE TITLE
tiny bug in ucam_webauth.php

### ISSUE THREAD

**Issue by ehk20** [gfarrell/WPRavenAuth#55]
Line 343 in app/lib/ucam_webauth.php has a tiny issue which is that more recent versions of PHP (post 5.1?) no longer tolerate curly brackets where it did before and need to be changed to square. More specifically this seems to be fatal:

```
343c343
<     $port = $_SERVER['SERVER_PORT'];
---
>     $port = $_SERVER{'SERVER_PORT'};

```
As ucam_webauth.php isn't maintained anywhere else, as far as I know, I propose fixing it here.

**Comment by gfarrell** [comment]
I haven't maintained this for a while, but if you want to open a PR I'm happy to accept and merge. Really someone else should take ownership of this repo I think.

**Comment by mo-g** [comment]
Opened #56 with the fix, rebased off Daniel's PR so if you merge his IBIS client update first it won't break my PR.

Have github account, can become canonical source? ;)
